"use strict";
let greeting = "Hello, World!";
console.log(greeting);
let num1, num2;
num1 = 2;
num2 = 3;
let sum = num1 + num2;
console.log(sum);
let differ = num2 - num1;
console.log(differ);
let prod = num1 * num2;
console.log(prod);
let quote = num1 ** num2;
console.log(quote);
let a = 2;
let b = 5;
a = a + b;
b = a - b;
a = a - b;
console.log(a);
console.log(b);
